services:
  _defaults:
    autowire: true
    autoconfigure: true

  Web\Module\Health\:
    resource: '../../../'
    exclude:
      - '../../../Resource'

  Web\Module\Health\Route\StatusRoute:
    public: true

  Web\Module\Health\Route\IncidentRoute:
    public: true

  Web\Module\Health\Route\DashboardRoute:
    public: true
